using System;
using System.Collections.Generic;
using System.Text;

namespace TRFinal_Tienda.Modelos
{
    public static class SeedersData
    {
        public static List<Games> GetInitialData()
        {
            return new List<Games>
            {
                new Games { Nombre = "The Witcher 3: Wild Hunt", Descripcion = "Juego de rol de mundo abierto con un rico lore y narrativa, protagonizado por el cazador de monstruos Geralt de Rivia." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/the-witcher-3-wild-hunt.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/epic-games.png", Precio = 39.99M },
                new Games { Nombre = "Doom Eternal", Descripcion = "Intenso juego de disparos en primera persona, enfrenta a los jugadores contra hordas de demonios del infierno." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/doom-eternal.jpg", Categorias = 3, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 29.99M},
                new Games { Nombre = "Stardew Valley", Descripcion = "Simulador de granja donde los jugadores pueden cultivar cultivos, criar animales y explorar el mundo del juego." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/stardew-valley.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 14.99M},
                new Games { Nombre = "Dark Souls III", Descripcion = "RPG de acción desafiante con una atmósfera oscura y combate exigente." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/dark-souls.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 14.99M},
                new Games { Nombre = "Minecraft", Descripcion = "Juego de construcción y exploración en un mundo de bloques." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/minecraft.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Microsoft_Store.png", Precio = 27},
                new Games { Nombre = "Grand Theft Auto V", Descripcion = "Mundo abierto en el que los jugadores pueden explorar, realizar misiones y causar estragos en la ciudad ficticia de Los Santos." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/grand-theft-auto.jpg", Categorias = 3, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 39.99M},
                new Games { Nombre = "Cyberpunk 2077", Descripcion = "RPG de mundo abierto ambientado en un futuro distópico en Night City, con elementos de ciencia ficción y acción." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/cyberpunk-2077.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/epic-games.png", Precio = 59.99M},
                new Games { Nombre = "Among Us", Descripcion = "Juego multijugador en línea de deducción social, donde los jugadores trabajan juntos en una nave espacial, pero algunos son impostores." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/amongus.jpg", Categorias = 3, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 4.99M},
                new Games { Nombre = "Hollow Knight", Descripcion = "Juego de plataformas y acción en 2D con un hermoso estilo de arte y una exploración meticulosa." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/hollow_knight.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 14.99M},
                new Games { Nombre = "The Elder Scrolls V: Skyrim", Descripcion = "RPG de mundo abierto con un vasto mundo por explorar, lleno de misiones, criaturas y secretos." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/tke-elder-scrolls.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 14.99M},
                new Games { Nombre = "Overwatch", Descripcion = "Juego de disparos en equipo con héroes únicos, cada uno con habilidades especiales, en emocionantes partidas multijugador." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/overwatch.jpg", Categorias = 3, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Blizzard_Battle.net.png", Precio = 39.99M},
                new Games { Nombre = "Celeste", Descripcion = "Juego de plataformas desafiante con una historia emotiva y una estética encantadora." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/celeste.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/epic-games.png", Precio = 19.99M},
                new Games { Nombre = "Portal 2", Descripcion = "Juego de rompecabezas en primera persona con mecánicas únicas basadas en portales." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/portal2.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 9.99M},
                new Games { Nombre = "Civilization VI", Descripcion = "Descripción: Juego de estrategia por turnos donde los jugadores construyen y desarrollan civilizaciones a lo largo de la historia." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/CivilizationVI.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/epic-games.png", Precio = 19.99M},
                new Games { Nombre = "Bioshock Infinite", Descripcion = "Shooter en primera persona con una historia cautivadora y elementos de ciencia ficción." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/bioshock_infinite.jpg", Categorias = 3, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 29.99M},
                new Games { Nombre = "Divinity: Original Sin 2", Descripcion = "RPG de mundo abierto con elementos tácticos y una narrativa profunda, donde las elecciones del jugador tienen un gran impacto." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/divinity-original-sin-ii.jpg", Categorias = 3, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 44.99M},
                new Games { Nombre = "Resident Evil 2 Remake", Descripcion = "Remake del clásico juego de survival horror con gráficos modernos y una experiencia aterradora." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/resident-evil-2.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 22.99M},
                new Games { Nombre = "Slay the Spire", Descripcion = "Juego de cartas y roguelike en el que los jugadores construyen mazos mientras exploran un mundo lleno de desafíos." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/SlayTheSpire.jpg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 24.99M},
                new Games { Nombre = "Cuphead", Descripcion = "Juego de plataformas con un estilo visual inspirado en los dibujos animados de la década de 1930 y desafiantes batallas contra jefes." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/cuphead.jpeg", Categorias = 1, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Microsoft_Store.png", Precio = 19.99M},
                new Games { Nombre = "Disco Elysium", Descripcion = "RPG de detective con un enfoque en la narrativa y la toma de decisiones, ambientado en un mundo único y oscuro." , Imagen = "https://dsadasdasdasd.000webhostapp.com/imgTrabajo/disco_elysium.jpg", Categorias = 3, ImgCompañia = "https://dsadasdasdasd.000webhostapp.com/imgVen/Steam.jpg", Precio = 39.99M}
            };
        }
    }
}
